
#TODO, write these tests
# add_players
# any_movement
# assign_x_pos_to_player_score_sprites
# center_image
# key
# key_1
# key_a
# key_d
# key_f
# key_left
# key_o
# key_q
# key_right
# key_s
# key_u
# key_up
# key_x
# math
# mix
# movement
# player_has_item
# player_in_front
# pyglet
# random
# remove_item_from_platform
# reverse_rotate_player_list
# right_answer
# rotate_items_left
# rotate_items_right
# rotate_players_left
# rotate_players_right
# set_item_spots
# set_player_score_sprites
# set_player_spots
# set_score_indices
# set_score_number
# set_score_spots
# set_score_values_x
# wrong_answer
