#!/usr/bin/python3
"""This file is just a container for categories of nouns that are not part of
    original Total English book series, returns None."""
everyday_objects = ['hammer',
                    'apple','apron','bus','car','dog','egg','fish','guitar',
                    'hat','ice','ink','jeans','key','lemon','moon','net',
                    'octopus','ocean','pig','quiz','racket','sun','tomato',
                    'umbrella','uniform','violin','water','box','yard','zoo']
musical_instruments=['piano','violin','flute','trumpet','drums','guitar']
parts_of_school = ['school gate',"student entrance",'classroom','library',
                   'playground','gym','swimming pool',"teacher's room",
                   "principal's office",'tennis court','baseball field',
                   'soccer field','roof','basement','bathroom']
literary_nouns = ['book','song','music','play','novel','story','paragraph',
                 'sentence','word','letter','love letter','mail']
burnable_things = ['paper','books','garbage','candle','food']
vegetables = ['carrot','cucumber','broccoli','Japanese radish','pumpkin',
              'green onion','onion']
desserts = ['cake','cookie','candy','ice cream']
animals = ['cat','dog','octopus','bird','monkey','elephant','tiger',
           'giraffe','horse','cow','chicken','duck','pig','fish','lion',
           'bug','rabbit','hamster','squirrel','turtle','beetle']
pets = ['cat','dog','rabbit','hamster','squirrel','bird','turtle',
        'beetle','snake','fish','spider']
common_nouns = [
    'accident',
    'acid rain',
    'addition',
    'address',
    'advantage',
    'adventure',
    'afternoon',
    'age',
    'air',
    'airpot',
    'album',
    'animal',
    'animation',
    'anime',
    'answer',
    'apartheid',
    'apartment',
    'apple',
    'arena',
    'arm',
    'art',
    'attention',
    'aunt',
    'baby',
    'bag',
    'ball',
    'balloon',
    'bamboo',
    'banana',
    'band',
    'bank',
    'baseball',
    'basketball',
    'bath',
    'beach',
    'bed',
    'beef',
    'bench',
    'best',
    'bike',
    'bird',
    'birthday',
    'black',
    'blue',
    'board',
    'boat',
    'book',
    'bookstore',
    'bottle',
    'box',
    'boy',
    'branch',
    'bread',
    'break',
    'breakfast',
    'bridge',
    'brother',
    'brush',
    'bubble',
    'building',
    'bus',
    'business',
    'butter',
    'button',
    'buzzer',
    'cafeteria',
    'cake',
    'calendar',
    'camera',
    'can',
    'cap',
    'car',
    'card',
    'care',
    'career',
    'carpenter',
    'carrot',
    'case',
    'castle',
    'cat',
    'cave',
    'CD',
    'cent',
    'center',
    'century',
    'chair',
    'chance',
    'charity',
    'cheeseburger',
    'chef',
    'chess',
    'chest',
    'child',
    'childhood',
    'children',
    'circle',
    'city',
    'class',
    'classmate',
    'classroom',
    'clerk',
    'climate',
    'clock',
    'cloth',
    'clothes',
    'cloud',
    'club',
    'coach',
    'coal',
    'coat',
    'coffee',
    'cola',
    'color',
    'comic',
    'communication',
    'company',
    'compartment',
    'computer',
    'conditioner',
    'condominium',
    'convenience',
    'cooking',
    'corner',
    'cotton',
    'cough',
    'country',
    'course',
    'cousin',
    'cracker',
    'crane',
    'culture',
    'curry',
    'custom',
    'customer',
    'cycling']
countable_nouns = [
    'ball',
    'bottle',
    'airpot',
    'birthday',
    'corner',
    'cave',
    'chef',
    'cat',
    'dog',
    'arena',
    'chance',
    'basketball',
    'country',
    'accident',
    'album',
    'balloon',
    'animal',
    'chair',
    'castle',
    'baby',
    'arm',
    'beach',
    'bench',
    'bike',
    'board',
    'boat',
    'boy',
    'girl',
    'bird',
    'button',
    'car',
    'card',
    'carrot',
    'box',
    'classroom',
    'cloud',
    'coat',
    'crane',
    'condominium',
    'customer']
same_as_singular = ['bison','deer','greenfly','grouse','moose',
                        'reindeer','sheep','cod','fish','goldfish',
                        'halibut','mullet','salmon','shellfish',
                        'trout','whitebait','aircraft','hovercraft',
                        'spacecraft','crossroads','dice','fruit',
                        'gallows','grapefruit','insignia','news',
                        'offspring','series','species','bourgeois',
                        'chassis','corps','patois','precis','rendevous',
                        'jeans']
country_foods = ['Chinese food','Japanese food','French food',
                        'Spanish food','Mexican food','American food',
                        'Italian food','Thai food']
unique_objects = ['sun','moon',]
