qa100_english_questions = [
    "What's your name?",
    "How do you do?",
    "How old are you?",
    "How are you today?",
    "Are you Ken?",
    "Do you like dogs?",
    "Are you Japanese?",
    "Do you like cats?",
    "Can you swim?",
    "Can you play football?",
    "Are you hungry?",
    "Do you speak English?"
    "Where do you live?",
    "Can you play the piano?",
    "Can you speak Japanese?",
    "Where are you from?",
    "Do you like science?",
    "Can you play the violin?",
    "How do you spell your name?",
    "What's your phone number?",
    "Are you a student?",
    "Do you have any brothers?",
    "Do you like ice cream?",
    "Can you play the guitar?",
    "Do you play tennis?",
    "What's your father's name?",
    "Do you like summer?",
    "What sport do you like the best?",
    "Do you have any sisters?",
    "Are you happy?",
    "Do you like music?",
    "What subject do you like the best?",
    "Can you cook?",
    "Do you speak French?",
    "Are you Chinese?",
    "What's your mother's name?",
    "How old is your sister?",
    "What time do you go to bed every day?",
    "Are you thirsty?",
    "What time do you get up every day?",
    "Do you like carrots?",
    "Are you American?",
    "Do you want a hot dog?",
    "What time do you go to school?",
    "Who's your homeroom teacher?",
    "Can you ski?",
    "Are you cold?",
    "What's your brother's name?",
    "Do you speak German?",
    "How old is your father?",
    "Are you Japanese or Chinese?",
    "Can you ride a bike?",
    "What's the matter?",
    "Are you hot?",
    "Does your father drive a car?",
    "Do you have a fever?",
    "What day is it today?",
    "What time do you get up on Sundays?",
    "Who's your English teacher?",
    "Does your sister speak French?",
    "When's your birthday?",
    "Where's New York?",
    "Do you drink coffee?",
    "Does your father smoke?",
    "Can I help you?",
    "Can you dive?",
    "How tall are you?",
    "Where's the bathroom?",
    "Does your brother speak English?",
    "Can I have some water?",
    "What's your hobby?",
    "Does your mother play the piano?",
    "How many pencils do you have?",
    "Whose book is this?",
    "What time is it now?",
    "What's the date today?",
    "Which season do you like the best?",
    "Do you like comics?",
    "Do you want more water?",
    "Does your father play golf?",
    "Did you study English yesterday?",
    "Will you turn on the light?",
    "Did you play baseball last week?",
    "Are you going to study math tonight?",
    "What did you eat for breakfast this morning?",
    "Do you like your homeroom teacher?",
    "Do you like Chinese food?",
    "Can you write your name in English?",
    "Can you read an English newspaper?",
    "What's the second month of the year?",
    "Have you been to Hokkaido?",
    "What are you doing now?",
    "What time did you get up this morning?",
    "Where did you go last Sunday?",
    "Have you been to Hawaii?",
    "Where did you go during the summer?",
    "Can I play with you?",
    "When were you born?",
    "Are you taller than your mother?",
    "Which is bigger, your foot or my foot?"
]
qa100_english_answers = [
    "My name is Aiko Hayashi.",
    "Very well. How do you do?",
    "I'm eleven years old.",
    "I'm fine, thank you.",
    "No. My name's Kenji.",
    "Yes, I do. I like dogs.",
    "Yes, I am. I'm Japanese.",
    "No, I don't. I don't like cats.",
    "Yes, I can. I can swim.",
    "No, I can't. I can't play football.",
    "No, I'm not. I'm not hungry.",
    "Yes, I do. I speak English a little.",
    "I live in Shibuya.",
    "Yes, I can. I can play the piano.",
    "Yes, I do. I speak Japanese.",
    "I'm from Tokyo, Japan.",
    "Yes, I do. I like science.",
    "No , I can't. I can't play the violin.",
    "A-i-k-o H-a-y-a-s-h-i.",
    "My phone number is 728-0250.",
    "Yes, I'm a student.",
    "No, I don't have any brothers.",
    "Yes, I like ice cream.",
    "No, I can't play the guitar.",
    "Yes, I play tennis.",
    "His name's Keita Hayashi.",
    "Yes, I like summer.",
    "I like baseball best.",
    "Yes, I have two sisters.",
    "Yes, I'm happy.",
    "Yes, I like music.",
    "I like English best.",
    "No, I can't cook.",
    "No, I don't speak French.",
    "No, I'm Japanese.",
    "Her name's Kiyoko.",
    "She's fifteen years old.",
    "I go to bed at 10 o'clock.",
    "Yes, I'm thirsty.",
    "I get up at 6:30 every day.",
    "No, I don't. I don't like carrots.",
    "No, I'm not. I'm not American.",
    "Yes, please. I want a hot dog.",
    "I go to school at 8 o'clock.",
    "Miss Nakamura is.",
    "No, I can't. I can't ski.",
    "No, I'm not. I'm not cold.",
    "His name's Masao.",
    "No, I don't. I don't speak German.",
    "He's 45 years old.",
    "I'm Japanese.",
    "Yes, I can. I can ride a bike.",
    "I have a stomachache.",
    "Yes, I am. I'm hot.",
    "Yes, he does. He drives a car.",
    "No, I don't. I don't have a fever.",
    "It's Wednesday.",
    "I get up at 9 o'clock on Sundays.",
    "Ms. Tamura is.",
    "No, she doesn't. She doesn't speak French.",
    "It's April 5th.",
    "It's in America.",
    "No, I don't drink coffee.",
    "No, he quit smoking.",
    "Yes, please.",
    "Yes, I can dive.",
    "I'm 150 centimeters tall.",
    "Come this way, please.",
    "Yes, he speaks English well.",
    "Sure.",
    "My hobby is collecting stamps.",
    "Yes, she plays the piano every day.",
    "I have a lot of pencils.",
    "It's mine.",
    "It's 4:30.",
    "It's August 16th.",
    "I like winter best.",
    "Yes, I love them.",
    "No, thank you.",
    "Yes, he plays golf.",
    "Yes, I studied English yesterday.",
    "Okay.",
    "No, I didn't play baseball last week.",
    "Yes, I'm going to study math tonight.",
    "I ate a piece of toast and some melon.",
    "Yes, he's very kind to us.",
    "Yes, I like Chinese food very much.",
    "Yes, I can write my name in English.",
    "No, I can't, but my father can.",
    "It's February.",
    "Yes, I've been to Hokkaido.",
    "I'm watching TV.",
    "I got up at 6 o'clock.",
    "I went to the beach last Sunday.",
    "No, I haven't been to Hawaii.",
    "I went to Kyoto and Nara.",
    "Sorry. I'm busy.",
    "I was born in 1990.",
    "Yes, I'm taller than my mother.",
    "My foot is bigger than yours."
]
qa100_japanese_questions = [
    "君、名前何ていうの？",
    "はじめまして。",
    "君何才？",
    "元気ですか？",
    "君はケン？",
    "犬すき？",
    "君は日本人？",
    "ネコすき？",
    "泳げる？",
    "フットボールできる？",
    "おなかすいた？",
    "英語しゃべれる？",
    "どこに住んでいるの？",
    "ピアノひける？",
    "日本語しゃべれる？",
    "どこからきたの？",
    "理科すき？",
    "バイオリンひける？",
    "どうやって君の名前のかくの？",
    "電話番号、何番？",
    "君は学生？",
    "兄弟いる？",
    "アイスクリームすき？",
    "ギターひける？",
    "テニスする？",
    "君のお父さんの名前何ていうの？",
    "夏ってすき？",
    "何のスポーツが一番すき？",
    "姉妹いる？",
    "うれしい？",
    "音楽すき？",
    "何の科目が一番すき？",
    "料理できる？",
    "フランス語しゃべれる？",
    "君は中国人？",
    "君のお母さんの名前、何ていうの？",
    "君のお姉さんいくつ？",
    "毎日、何時にねるの？",
    "のどかわいた？",
    "毎日、何時におきるの？",
    "人参すき？",
    "君はアメリカ人？",
    "ホットドッグほしい？",
    "何時に学校に行くの？",
    "君のホームルームの先生はだれ？",
    "スキーできる？",
    "寒い？",
    "君のお兄さんの名前は何ていうの？",
    "ドイツ語しゃべれる？",
    "君のお父さんいくつ？",
    "君は日本人、それとも中国人なの？",
    "自転車にのれる？",
    "どうしたの？",
    "暑い？",
    "君のお父さん、自動車運転する？",
    "熱があるの？",
    "今日は何曜日？",
    "日曜日には、何時におきるの？",
    "君の英語の先生はだれ？",
    "君のお姉さん、フランス語しゃべれる？",
    "お誕生日はいつ？",
    "ニューヨークはどこにあるの？",
    "コーヒーのむ？",
    "君のお父さん、たばこすう？",
    "手伝おうか？",
    "飛びこみできる?",
    "背の高さはどのくらいある？",
    "お手洗いはどこ？",
    "君のお兄さん、英語しゃべれる？",
    "お水のんでもいい？",
    "趣味はなに？",
    "君のお母さん、ピアノひく？",
    "何本鉛筆もってる？",
    "この本、誰の？",
    "今、何時？",
    "今日は何日？",
    "どの季節が一番すき？",
    "マンガすき？",
    "もっと水ほしい？",
    "君のお父さん、ゴルフする？",
    "昨日、英語の勉強した？",
    "電気、つけてくれる？",
    "先週、野球した？",
    "今夜、数学の勉強するつもり？",
    "今朝の朝ごはん、何たべた？",
    "君のホームルームの先生、すき？",
    "中華料理すき？",
    "英語で名前かける？",
    "英字新聞、よめる？",
    "１年の中で２番目の月は何？",
    "北海道に行ったことある？",
    "今、何してるの？",
    "今朝、何時におきたの？",
    "先週の日曜日、どこに行ったの？",
    "ハワイに行ったことある？",
    "夏のあいだに、どこに行ったの？",
    "いっしょに、あそべる？",
    "いつ生まれたの？",
    "君の方がお母さんより背が高い？",
    "君の足と僕の足とどっちが大きい？",
]
qa100_japanese_answers = [
    "私の名前は、はやし・アイコです。",
    "はじめまして。",
    "１１歳だよ。",
    "うん、元気だよ。",
    "いいえ。僕の名前はケンジです。",
    "うん、犬はすきだよ。",
    "うん、日本人だよ。",
    "いいえ、ネコはすきじゃない。",
    "うん、泳げるよ。",
    "いいえ、フットボールはできない。",
    "いいえ、おなかはすいていない。",
    "うん、英語は少ししゃべれるよ。",
    "渋谷に住んでいます。",
    "うん、ピアノはひけるよ。",
    "うん、日本語は話すよ。",
    "日本の東京からです。",
    "うん、料理はすきだよ。",
    "いいえ、バイオリンはひけない。",
    "A-i-k-o H-a-y-a-s-h-i.",
    "うちの電話番号は、７２８−０２５０。",
    "うん、学生だよ。",
    "いいえ、兄弟はいないよ。",
    "うん、アイスクリームすき。",
    "いいえ、ギターはひけないんだ。",
    "うん、テニスするよ。",
    "お父さんの名前は、ハヤシ・ケイタです。",
    "うん、夏はすき。",
    "野球が一番すき。",
    "うん、２人姉妹がいるよ。",
    "うん、うれしい。",
    "うん、音楽すきだよ。",
    "英語が一番すき。",
    "いいえ、料理できないよ。",
    "いいえ、フランス語しゃべれないよ。",
    "いいえ、僕は日本人です。",
    "お母さんの名前はキヨコです。",
    "お姉さんは１５歳です。",
    "１０時に寝ます。",
    "うん、のどがかわいたよ。",
    "毎日、６時３０分におきます。",
    "いいえ、嫌い。僕、人参がきらい。",
    "ちがうよ。僕、アメリカ人じゃないよ。",
    "うん。僕、ホットドッグがほしいよ。",
    "８時に学校に行きます。",
    "ナカムラ先生です。",
    "いいえ、できないの。僕、スキーできないの。",
    "いいえ、寒くない。僕、寒くないよ。",
    "お兄さんの名前は、マサオです。",
    "いいえ。僕、ドイツ語しゃべれないよ。",
    "お父さんは４５歳です。",
    "僕は日本人です。",
    "うん、のれるよ。僕自転車にのれるよ。",
    "おなかがいたい。",
    "うん、暑い。僕、暑いよ。",
    "うん、するよ。お父さん、自動車運転するよ。",
    "いいえ、ないよ。僕、熱ないよ。",
    "水曜日だよ。",
    "日曜日には９時におきるよ。",
    "タムラ先生です。",
    "いいえ、お姉さんはフランス語しゃべれないよ。",
    "４月５日です。",
    "アメリカにあります。",
    "いいえ、コーヒーはのまないんだ。",
    "いいえ、お父さんはたばこをすうのをやめたよ。",
    "うん、おねがい。",
    "うん、飛びこみできるよ。",
    "１５０cmだよ。",
    "こちらです。どうぞ。",
    "うん、お兄さん、上手に英語しゃべれるよ。",
    "いいよ。",
    "趣味は、切手のコレクションだよ。",
    "うん、お母さんは毎日ピアノをひくよ。",
    "たくさん鉛筆もってるよ。",
    "僕のです。",
    "４時３０分です。",
    "８月１６日です。",
    "冬が一番すき。",
    "うん、大好きだよ。",
    "いいえ、けっこうです。",
    "うん、お父さん、ゴルフするよ。",
    "うん、昨日、英語の勉強したよ。",
    "はい。",
    "いいえ、先週、野球したかったよ。",
    "うん、今夜、算数の勉強するつもり。",
    "トースト１枚とメロンをたべたよ。",
    "うん、先生、僕たちにすごくやさしいんだ。",
    "うん、中華料理、すごくすき。",
    "うん、かけるよ。",
    "いいえ、よめないよ、だけど、お父さんはよめるよ。",
    "２月です。",
    "うん、北海道に行ったことあるよ。",
    "テレビを見ているの。",
    "６時に、おきたよ。",
    "先週の日曜日、海岸に行ったの。",
    "いいえ、ハワイには行ったことがないの。",
    "京都と奈良に行ったの。",
    "ごめんね。忙しいんだ。",
    "１９９０年です。",
    "うん、僕の方がお母さんより背が高いよ。",
    "僕の足の方が君のより大きいよ。",
]
