eng_book_1= (
    "I like soccer",
    "I like ...",
    "Do you play soccer?",
    "Yes, I do.",
    "No, I don't.",
    "I don't play soccer.",
    "I have a cat.",
    "I have an eraser.",
    "I have two dogs.",
    "How many CDs do you have?",
    "I have ten CDs.",
    "I have no CDs.",
    "What do you watch on TV?",
    "I watch soccer games.",
    "Stand up.",
    "Stand up, please.",
    "Don't run.",
    "Don't run, please.",
    "I'm Ben Wilson.",
    "I'm from Canada.",
    "Are you a rock fan?",
    "Yes, I am.",
    "No, I'm not.",
    "I'm not a regular player.",
)
eng_book_2 = (
    "I was happy.",
    "Miku and Hiro were tired.",
    "Were you sleepy?",
    "Yes, I was.",
    "No, I wasn't.",
    "It looks delicious!",
    "They look like one big family.",
    "I was reading a book.",
    "Were you studying?",
    "Yes, I was.",
    "No, I wasn't.",
    "When we say 'no,' we shake our head.",
    "We shake our head when we say 'no.'",
    "I think (that) gestures are important for communication.",
    "There is a picture on the wall.",
    "There are two pictures on the wall.",
    "Is there a picture on the wall?",
    "Yes, there is.",
    "No, there isn't.",
    "We will arrive at 3:15.",
    "We will serve lunch.",
    "Will we arrive at 3:50?",
    "Yes, we will.",
    "No, we won't.",
    "I won't have lunch.",
    "I'm going to stay at my aunt's house.",
    "I'm not going to stay at a hotel.",
    "Are you going to stay in London?",
    "Yes, I am.",
    "No, I'm not.",
)
eng_book_3 = (
    "My friends call me Hiro.",
    "This book is written in English.",
    "This table was made by my father.",
    "Is English spoken in that country?",
    "Yes, it is.",
    "No, it isn't.",
    "Do you know how to make a paper crane?",
    "I don't know what to do.",
    "Hiro taught me how to make a paper crane.",
    "I've just arrived.",
    "I've already done my homework.",
    "Have you washed the dishes yet?",
    "Yes, I have.",
    "No, I haven't.",
    "I haven't cleaned the room yet.",
    "I've been in this city for three days.",
    "I've lived in this city since I was ten years old.",
    "How long have you been here?",
    "I've been here for four days.",
    "Have you ever been to the U.S.?",
    "I've never seen the movie.",
#    "It is important (for us) to understand other cultures.",
#    "The man standing over there is my father.",
#    "I received a letter written in English.",
#    "I asked my father to help me.",
#    "My mother told me to clean my room.",
#    "We want you to join us.",
#    "We need a person who speaks English.",
#    "The woman who is standing over there is my mother.",
#    "Stevie wrote songs which touched people around the world.",
#    "Stevie wrote songs that touched people around the world.",
#    "These are some pictures which I took in the park.",
#    "The cake which your uncle made is delicious.",
#    "The people that we met yesterday were very kind to us.",
#    "The movie that I saw last week was very interesting.",
#    "The people we met yesterday were very kind to us.",
#    "The movie I saw last week was very interesting.",
#    "I know why Hiro didn't come.",
)
